[package]
name = "magelang_wasm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
magelang_semantic = { path = "../magelang_semantic" }
indexmap = "1.9.3"
