struct Token {
    pub kind: TokenKind,
    pub pos: Pos,
}

enum TokenKind {
    // keywords
    TokenFn,
    TokenVar,
    TokenIf,
    TokenWhile,
    TokenReturn,
    TokenType,
    TokenStruct,
    TokenTuple,
    // constant
    TokenIdent(String),
    TokenStringLit(String),
    TokenNumberLit(String),
    TokenFloatLit(String),
    TokenTrue,
    TokenFalse,
    // symbols
    TokenOpenBrace,
    TokenCloseBrace,
    TokenOpenBlock,
    TokenCloseBlock,
    TokenAssign,
    TokenEndl,
    TokenEOI,
    TokenComma,
    TokenColon,
    TokenDot,
    // operators
    TokenPlus,
    TokenPlusAssign,
    TokenMinus,
    TokenMinusAssign,
    TokenMul,
    TokenMulAssign,
    TokenDiv,
    TokenDivAssign,
    TokenMod,
    TokenModAssign,
    TokenBitAnd,
    TokenBitAndAssign,
    TokenBitOr,
    TokenBitOrAssign,
    TokenBitNot,
    TokenBitXor,
    TokenBitXorAssign,
    TokenSHL,
    TokenSHLAssign,
    TokenSHR,
    TokenSHRAssign,
    TokenAnd,
    TokenOr,
    TokenNot,
    TokenGT,
    TokenLT,
    TokenGTEq,
    TokenLTEq,
    TokenEq,
    TokenNotEq,
    // comments
    TokenComment(String),
    // primitives
    TokenBool,
    TokenI8,
    TokenI16,
    TokenI32,
    TokenI64,
    TokenU8,
    TokenU16,
    TokenU32,
    TokenU64,
    TokenF32,
    TokenF64,
}

struct Pos {
    pub line: i32,
    pub col: i32,
}
